name = "quiz-app"
main = "src/index.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

# ========== 静态资源 ==========
[assets]
directory = "./public"
not_found_handling = "none"
# binding = "ASSETS"

# ========== D1 ==========
[[d1_databases]]
binding = "DB"
database_name = "quiz-db"

# ========== 定时任务 ==========
[triggers]
crons = ["0 3 * * *"]

# ========== 变量 ==========
[vars]
ALLOWED_ORIGINS = ""
AFDIAN_USER_ID = ""
AFDIAN_TOKEN = ""
AFDIAN_PLAN_MONTH = ""
AFDIAN_PLAN_YEAR = ""
PASSWORD_PEPPER = ""